### ISSUE TITLE
Add option for whether a space is automatically inserted after the colon on property autocomplete

### ISSUE THREAD

**Issue by jenniferaslan** [atom/autocomplete-css#49]
The default behavior after autocompleting a CSS property is to insert a colon and a space. I know that many people like to format their CSS that way, but since I don't have each property on its own line in the code, I rely on the space after the semicolon to show me where they begin and end, and having a space after the colon messes up my ability to visually scan the file for what I'm looking for. Please add an option for whether you want the space after the colon on autocomplete or not. Thanks.

**Comment by lee-dohm** [comment]
Thank you very much for the feedback and the idea.

I agree that this would be a useful feature to have, but I don't think that this package is the place to add it. If every autocomplete provider has to anticipate and support every difference in format for the things it inserts, there will be a lot of duplicated code, mismatching functionality and a combinatorial explosion in configuration settings. I think that formatting code is best served by a formatter or beautifier whose specific job is to enforce the format you're seeking.

I do think that it would be useful to maybe add a hook to the [autocomplete-plus package](https://github.com/atom/autocomplete-plus) that informs a beautifier that some code has been inserted or is about to be inserted. This would give the beautifier the chance to format the code right away instead of waiting for a post-process to do it. (The beautifiers might need to be modified also to support such a thing.)

Thanks again for your feedback. I've opened up [a topic on Discuss](https://discuss.atom.io/t/having-beautifiers-format-code-on-automated-insert/28103) to give the community a chance to give input on how something like this might be designed.
