### ISSUE TITLE
autocomplete-css doesn't work for css file.

### ISSUE THREAD

**Issue by JustinYangJing** [atom/autocomplete-css#74]
autocomplete-css doesn't work for *.css file, but it works fine for *.scss file. The version is 0.13.1.

**Comment by winstliu** [comment]
Hi @JustinYangJing, can you please elaborate?  Does it still not work in safe mode (`atom --safe`)?  What Atom version are you using (`atom --version`)?  Can you provide a CSS file that doesn't work for you?  Thanks!

**Comment by JustinYangJing** [comment]
Hi,  @50Wliu  I'm sorry for replying to you late . It works in safe mode . The following is the Atom's version information.
Atom    : 1.12.6
Electron: 1.3.9
Chrome  : 52.0.2743.82
Node    : 6.5.0
 
CSS file is normal format .such as "background-color:#ff0000;", The key word "background-color" cant be auto completed when i type “back..”;

autocomplete-css for *.css file.

[css file](https://raw.githubusercontent.com/JustinYangJing/Resource/master/Image/issue/1.png)

autocomplete-css for *.scss
[scss filr](https://raw.githubusercontent.com/JustinYangJing/Resource/master/Image/issue/2.png)

**Comment by winstliu** [comment]
Ok, since this works in safe mode, that means one of the community packages you installed is causing the issue.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
