### ISSUE TITLE
can not autocomplete border values ?

### ISSUE THREAD

**Issue by ccqgithub** [atom/autocomplete-css#89]
```
div {
  border: 1px sol
  background: trans
}
```
(border) it can not support the values: solid, dashed ... 
(background) can not support the values: transparent ... 
etc...

**Comment by winstliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
