### ISSUE TITLE
Package.getActivationCommands is deprecated.

### ISSUE THREAD

**Issue by zetay** [atom/autocomplete-css#9]
Use `activationCommands` instead of `activationEvents` in your package.json
Commands should be grouped by selector as follows:

``` json
  "activationCommands": {
    "atom-workspace": ["foo:bar", "foo:baz"],
    "atom-text-editor": ["foo:quux"]
  }
```

```
Package.getActivationCommands (D:\GreenSoft\Atom\resources\app\src\package.js:766:9)
Package.hasActivationCommands (D:\GreenSoft\Atom\resources\app\src\package.js:691:20)
```

**Comment by thomasjo** [comment]
Thanks for reporting, but these are _false positives_ — this package has neither activation commands nor config schema.

---

/cc @izuzak @atom/non-github-maintainers
Could this be an issue in a provider used by this package?

**Comment by izuzak** [comment]
> Could this be an issue in a provider used by this package?

@thomasjo I'm not sure what's causing the incorrect attribution in this case. It would be great if we can reproduce this problem so that we can investigate further. Seems like you asked for the list of packages in another issue opened by @zetay. :+1: Once we have that list, we can try to reproduce and then open an issue over in https://github.com/atom/deprecation-cop with more information.
